name: Accenture
channels:
  - defaults
dependencies:
  - python
  - pandas
  - pip
  - ipykernel
  - numpy
  - matplotlib
  - scipy
  - tqdm
prefix: C:\Users\vkeenan\AppData\Local\miniconda3\envs\Accenture
